language: R
sudo: false
cache: packages
r:
  - release

addons:
  apt:
    packages:
     - ccache
     - libglu1-mesa-dev

env:
  global:
    - _R_CHECK_TIMINGS_=0
    - _R_CHECK_FORCE_SUGGESTS_=false
    - _R_CHECK_TESTS_NLINES_=999
    - NOT_CRAN=true
    - MAKEFLAGS="-j 2"
    - RGL_USE_NULL=TRUE

before_script:
  - rm inst/doc/*.* || true
  - Rscript -e 'if (!require("roxygen2")) install.packages("roxygen2")'
  - Rscript -e 'if (!require("covr")) install.packages("covr")'
  - Rscript -e 'if (!require("pkgdown")) install.packages("pkgdown")'
  - Rscript -e 'if (!require("devtools")) install.packages("devtools")'
  - Rscript -e 'devtools::document()'

stages:
  - test
  - name: document
    if: branch = mosmafs-package AND type IN (push, api, cron)

jobs:
  include:
    - stage: test
      env: github-mlr
      script:
        - Rscript -e 'devtools::install_github("berndbischl/BBmisc")'
        - Rscript -e 'devtools::install_github("berndbischl/ParamHelpers")'
        - Rscript -e 'devtools::install_github("mlr-org/mlr")'
        - Rscript -e 'message("INSTALLED PACKS:"); installed.packages()[,2:3]'
        - travis_wait 100 R CMD build .
        - travis_wait 100 R CMD check mosmafs*.tar.gz --as-cran --run-donttest
        - grep -q -R "WARNING" "mosmafs.Rcheck/00check.log" ; [ $? -ne 0 ]
    - stage: test
      env: cran-mlr
      script:
        - Rscript -e 'message("INSTALLED PACKS:"); installed.packages()[,2:3]'
        - travis_wait 100 R CMD build .
        - travis_wait 100 R CMD check mosmafs*.tar.gz --as-cran --run-donttest
        - grep -q -R "WARNING" "mosmafs.Rcheck/00check.log" ; [ $? -ne 0 ]
    - stage: test
      env: cran-mlr
      script:
        - travis_wait 100 Rscript -e 'covr::codecov(quiet = FALSE)'
    - stage: document
      env: cran-mlr
      script:
        - true
      before_deploy:
        - rm -rf doc | true
        - rm -rf inst | true
        - travis_wait 100 Rscript -e 'roxygen2::roxygenize(); devtools::install(quick = TRUE); pkgdown::build_site()'
        - travis_wait 100 Rscript -e 'tools::buildVignettes(dir = ".")'
        - mkdir -p inst/doc
        - mv -f vignettes/*.html inst/doc
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: docs
        on:
          branch: mosmafs-package
      after_deploy:
        - git checkout mosmafs-package  # otherwise we're in detached head
        - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
        - git config user.name Travis
        - git config user.email '<>'
        - git config credential.helper "store --file=.git/credentials"
        - echo "https://${GITHUB_TOKEN}:@github.com" >> .git/credentials
        - git config push.default matching
        - |
          git difftool -yx "diff -qI '20[0-9][0-9]-[0-1][0-9]-[0-3][0-9]\\|environment. 0x\\|bytecode. 0x\\|time. [0-9.]\\+'" | \
          grep ' and inst/doc' | sed -e 's|.*and inst/doc|inst/doc|' -e 's/ differ$//' | xargs git add
        - git ls-files --deleted | grep '^inst/doc/' | xargs git add
        - git ls-files --others  | grep '^inst/doc/.*\.html$' | xargs git add
        - git add --force man/*
        - git add DESCRIPTION NAMESPACE
        - git commit -m "update auto-generated documentation [ci skip]" || true
        - git push

on_success: change
on_failure: always

notifications:
  email: false

